name: LifeSteal
version: '1.0.0'
main: me.honeyberries.lifeSteal.LifeSteal
api-version: '1.21'
authors: [ HoneyBerries ]
commands:
  heart:
    aliases: [health, hp, hearts]
    description: Set the number of hearts a player has.
    usage: /heart <action> <amount> <player (optional)>
    permission: lifesteal.heart
    permission-message: Sorry, you don't have permission to adjust player health!.
  withdraw:
    aliases: [wd, draw]
    description: Lets you withdraw hearts.
    usage: /withdraw <amount>
    permission: lifesteal.withdraw
    permission-message: Sorry, you can't withdraw hearts!
permissions:
  lifesteal.heart:
    description: Allows the use of the /heart command to modify player health.
    default: op
  lifesteal.edit:
    description: Allows modification of the lifesteal configuration
    default: op
  lifesteal.withdraw:
    description: Lets you withdraw hearts using /withdraw
    default: true